# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b17e761c40a3be9717f632964e8427d3dfbac6a38bec36928a07a6c81fc381b30616b6607696d4c76a68797ab618684093c3cdc03752e9f11d2cbe9dc64e60a

test:
  secret_key_base: 03a134b5e6c4b488c3ab39197eb9839c0c4ba182ed137900ac2cc0ee1554e86d809b2e4055778319a43c1440ca3237a4fb4825e7f5a74f6c70b2ce19ac13fec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
